# Handling through Centralized cinfig
#server:
#  port: 8092
  
spring:
  application:
    name: notificationservice
  cloud:
    config:
      uri: http://localhost:8888

# Handling through Centralized cinfig
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/