server:
  port: 8888      

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vaanhit/microservice
          search-paths:
           - config 
            
            
            
 ##########################################################
 #If using username/password for authentication.
 #spring:
 # cloud:
 #   config:
 #     server:
 #       git:
 #         uri: https://github.com/vaanhit/microservice
 #         username: xxxxxx   
 #         password: xxxxxx 
 ##########################################################                    