server:
  port: 8888      
# Set configurationfile from localsystem.
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ../config/
            
##########################################################
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: C:/WORK_ENV/workspace/microservice/ 
          #https://github.com/vaanhit/microservice
#          search-paths:
#           - config 
            
            
            
 ##########################################################
 #If using username/password for authentication.
 #spring:
 # cloud:
 #   config:
 #     server:
 #       git:
 #         uri: https://github.com/vaanhit/microservice
 #         username: xxxxxx   
 #         password: xxxxxx 
 ##########################################################                    