spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demoTMDB
    username: root
    password: root
    